### PR TITLE
Initial setup

### PR DESCRIPTION
**Pull request by Zsailer**
I started preparing this repo for development. @jaipreet-s and @yuvipanda 

So far, I've cherry-picked @yuvipanda's commits from jupyterhub/jupyterhub#2542 and jupyterlab/jupyterlab-telemetry#1 (I wanted to make sure you got credit for your work! 😃). This includes an initial Configurable `EventLog` object that Jupyter applications can use to begin logging events. I think this is a good starting point. 

The JS module is essentially blank. It includes a jupyterlab handler that probably doesn't belong in this repo (it just came with the block of commits I cherry-picked). 

I propose we merge this PR as is and iterate in separate PRs—I haven't changed the current API to fit the method names described in the JEP. That's the next step. Then, we can begin building up from there.

### CODE REVIEW

**Comment by yuvipanda** [comment]
Ooooh I like this!!! 

I'm happy to merge it if you take the WIP off the title.

Thanks for kicking this off

**Comment by Zsailer** [comment]
Awesome, @yuvipanda. Merge away! 😃

**Comment by yuvipanda** [comment]
Done, Thank you!

**Comment by yuvipanda** [comment]
And I appreciate the cherry-picks :)

**Pull request merged**
