### PR TITLE
Ensure unique loggers

### LINKED ISSUE #44: EventLog is using a shared logger instance
If multiple packages instantiate `EventLog`, they end up sharing the same [logger](https://github.com/jupyter/telemetry/blob/ede6d17312cd57fe1441dc1222280834ca3d6f03/jupyter_telemetry/eventlog.py#L59), meaning they write to each other's handlers.  We should ensure a unique logger for each instance of `EventLog`.

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #44.  

@Zsailer if you could please add me as a maintainer on https://pypi.org/project/jupyter-telemetry I can cut a release.

### CODE REVIEW

**Comment by yuvipanda** [comment]
Thanks for the PR @blink1073! I've merged this, and given you rights on pypi as well.

**Comment by blink1073** [comment]
Thanks @yuvipanda!  It looks like it didn't go through.  My username is blink1073 there as well.

```
HTTPError: 403 Client Error: The user 'blink1073' isn't allowed to upload to project 'jupyter-telemetry'.
```

**Comment by blink1073** [comment]
cc @Zsailer ^^

**Comment by Zsailer** [comment]
@blink1073, done!

**Comment by blink1073** [comment]
...and released, cheers!

**Comment by Zsailer** [comment]
@blink1073, great stuff! Thank you, and welcome to the jupyter telemetry team! 🚀 😎

**Pull request merged**
